# Generated by Django 3.2.6 on 2021-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_assignment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_color',
            field=models.CharField(default='#ffffff', max_length=255),
        ),
    ]
