# Generated by Django 3.2.6 on 2021-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_classroom_classroom_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.CharField(default='ungraded', max_length=255),
        ),
    ]
